export * from './spec-card';
export * from './cpu-spec-card';
export * from './gpu-spec-card';
export * from './ram-spec-card';
export * from './storage-spec-card';
export * from './mainboard-spec-card';
export * from './psu-spec-card';
export * from './case-spec-card';
export * from './cooling-spec-card';
